# -*- coding: utf-8 -*-
"""ET_PYTHONLAB.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-V-PWGw8JL0LW4UCygoZKRkMOHa2yeAa

#NAME ->AARZOO
#REG NO. ->PIET18CS005
SET NO.->11

#1 Develop a website for Leave management system. Home
page contains title as Apply for Leave then it include
different fields like Employee name, employee id,
Department name , From Date , To Date , Total leave
taken , Authority Name, Reason of Leave . On save button
all the information to be saving in database and display
the list of employee name their Id, department date wise
on clicking on show button.
"""

import os
os.mkdir('static')
os.mkdir('templates')

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

dataset= pd.read_csv('/content/DATASET education - Sheet1.csv')
print(dataset)

import sqlite3

conn = sqlite3.connect('/content/DATASET education - Sheet1.db')
print ("Opened database successfully")

conn.execute('CREATE TABLE employess (name TEXT, department TEXT)')
print ("Table created successfully");
conn.close()

import sqlite3
conn = sqlite3.connect('/content/DATASET education - Sheet1.db')
print ("Opened database successfully")
r_set=conn.execute('''select name from sqlite_master 
		where type = 'table' ''')
for row in r_set:
    print(row)

r_set=conn.execute('''INSERT INTO students (`name`, `department`) VALUES
  ('John Deo', 'HR'),
  ('Mohan', 'MANERGICAL'),
  ('Rows Noump', 'Computer')

print("No of Records added : ",r_set.rowcount)

r_set=conn.execute('''SELECT * from employess''');
for row in r_set:
    print(row)

var='''
<html>
   <body>
     
         <h1>Welcome to the Employee DataBase </h1>
         <h2><a href = "{{url_for('new_employee')}}">Add Employee in DataBase</a></h2>
         <h2><a href = "{{url_for('del_employee')}}">Delete DataBase</a></h2>
         <h2><a href = "{{url_for('list')}}">Show Employee List from  DataBase</a></h2>
   </body>
</html>
'''
file=open("templates/home.html","w")
file.write(var)
file.close()

var='''
<html>
   <body>
      <form action = "{{ url_for('addrec') }}" method = "POST">
         <h3>Employee Information</h3>
         Name<br>
         <input type = "text" name = "nm" /></br>
         
         Department<br>
         <textarea name = "department" ></textarea><br>
         
         <input type = "submit" value = "submit" /><br>
      </form>
   </body>
</html>
'''
file=open("templates/student.html","w")
file.write(var)
file.close()

var='''
<html>
   <body>
      <table border = 1>
         <thead>
            <td>Name</td>
            <td>Department</td>
            
         </thead>
         
         {% for row in rows %}
            <tr>
               <td>{{row["name"]}}</td>
               <td>{{row["department"]}}</td>
              	
            </tr>
         {% endfor %}
      </table>
      
      <a href = "/">Go back to home page</a>
   </body>
</html>
'''
file=open("templates/list.html","w")
file.write(var)
file.close()

var='''
<html>
   <body>
      <h1> {{msg}}</h1>
      
      <a href = "/">Go back to home page</a>
   </body>
</html>
'''
file=open("templates/result.html","w")
file.write(var)
file.close()

!pip install flask-ngrok 
import sqlite3
from flask import Flask,render_template,request,url_for
from flask_ngrok import run_with_ngrok
app = Flask(__name__)
run_with_ngrok(app)

@app.route('/')
def home():
  
    return  render_template('home.html')

@app.route('/enternew')
def new_employee():
   return render_template('employee.html')    

@app.route('/addrec',methods = ['POST', 'GET'])
def addrec():
   if request.method == 'POST':
      #try:
         nm = request.form.get('nm')
         addr = request.form.get('department')
         
         
         conn = sqlite3.connect('/content/DATASET education - Sheet1.csv')  
            
         cur = conn.cursor()
         cur.execute("INSERT INTO employee (name,addr,city,pin) VALUES (?,?,?,?)",(nm,department))
         conn.commit()  
         msg = "Employee successfully Added"  
         return render_template("result.html",msg = msg)
         conn.close()

@app.route('/list')
def list():
   
   
    conn = sqlite3.connect('/content/DATASET education - Sheet1.csv')  
    conn.row_factory = sqlite3.Row  
    cur = conn.cursor()  
    cur.execute("select * from employees")  
    rows = cur.fetchall()  
    return render_template("list.html",rows = rows)  

@app.route('/del_employee')
def del_employee():
    conn = sqlite3.connect('/content/DATASET education - Sheet1.csv')  
      
    cur = conn.cursor()  
    cur.execute("delete from employees")
    conn.commit()    
    return render_template("list.html") 

if __name__ == '__main__':
   app.run()

var='''
<html>  
   <body>  
      <form action = "{{url_for('login')}}" method="Get">  
         <table>  
        <tr><td>Name</td>  
        <td><input type ="text" name ="uname"></td></tr>  
        <tr><td>Password</td>  
        <td><input type ="department" name ="pass"></td></tr> 
        <tr><td>Tell About You</td>  
        <td><input type ="about you" name ="pass"></td></tr>  
        <tr><td><input type = "submit"></td></tr>  
    </table>  
      </form>  
   </body>  
</html>  
'''

file=open("templates/login.html","w")
file.write(var)
file.close()

#!ngrok autotoken !1rhV16XMkEqKZ7TDJTWIBvaHbQh_3y5t8V3zE5kmxUAoZwWLx

!ngrok authtoken 1rhV16XMkEqKZ7TDJTWIBvaHbQh_3y5t8V3zE5kmxUAoZwWLx

!pip install flask-ngrok 
from flask import Flask,render_template,request
from flask_ngrok import run_with_ngrok
app = Flask(__name__)
run_with_ngrok(app)

@app.route('/')
def home():
  
    return render_template("login.html") 

@app.route('/login', methods=["GET"])  
def login():  
      
      uname=request.args.get('uname')
     
     
      passwrd=request.args.get('pass')

      
     
      if uname=="aarzoo" and passwrd=="google":  
          return "Welcome %s" %uname 
      return "User name does not exist"
if __name__ == '__main__':  
   app.run()

!pip install flask_ngrok

"""#2 Write a Python Program to Read a File and Capitalize the
First Letter of Every Word in the File
"""

fname = input("Enter file name: ")
 
with open(fname, 'r') as f:
    for line in f:
        l=line.title()
        print(l)